name: avidsapp
favicon: null
layout_spectrum: 1
typography_spectrum: 0.55012
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#090804'
    - '#f6f6f6'
    - '#789ec5'
    - '#cfb084'
    - '#496c92'
  brandStrength: 0.7675592687446624
  lightness: 0.5294427119661123
  saturation: 0.5652204682119191
  rhythmicContrast: 0.3407706150319427
purpose: []
